CREATE TABLE IF NOT EXISTS session1
(
	id INT(11) NOT NULL AUTO_INCREMENT,
	firstname VARCHAR(45) COLLATE utf8_unicode_ci NOT NULL,
	lastname VARCHAR(45) COLLATE utf8_unicode_ci NOT NULL,
	PRIMARY KEY ( id )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO session1 (firstname, lastname) 
VALUES
('Bucky', 'Roberts'),
('Noah', 'Parker'),
('Kelsey', 'Burger'),
('Corey', 'Smith'),
('Harry', 'Potter'),
('Henry', 'Jackson'),
('Cynthia', 'Alvarez'),
('Teresa', 'Smith'),
('Gary', 'Foster'),
('Sherry', 'Gibbons'),
('Jack', 'Nicholson'),
('Penny', 'Green'),
('Alexander', 'Evans'),
('Jeremy', 'White'),
('Omar', 'Badshah'),
('Preston', 'Harrison'),
('Manuel', 'Rodriguez'),
('David', 'Jones'),
('Nick', 'Flanders'),
('Paul ', 'Brown'),
('Sara', 'Rehm'),
('Haley', 'Carter'),
('Julian', 'Thomas'),
('George', 'Lucas'),
('Perry', 'Jordan'),
('Christopher', 'Layt'),
('Devon', 'Myers'),
('Debra', 'Talkington'),
('Peter', 'Johnson'),
('Harry', 'Brown'),
('Kay', 'Billings'),
('Desmond', 'Rafferty'),
('Lisa', 'Washington'),
('Jackson', 'Taylor'),
('Michael', 'Davis'),
('Candice', 'Thompson'),
('Terry', 'Mitchell'),
('Ruth', 'Bolen'),
('James', 'Hamilton'),
('Harvey', 'Akins'),
('Timothy', 'Smothers'),
('Stephanie', 'Nichols'),
('Ken', 'Davidson'),
('Angel', 'Martin'),
('Cathy', 'Douglas'),
('Kendall', 'Norton'),
('Desire', 'Morton'),
('Patty ', 'Zrock'),
('Evan', 'Bayh'),
('Kevin', 'Masters'),
('Paula', 'Barker'),
('John', 'Jacobs'),
('Dana', 'Brunswick'),
('David', 'Turner'),
('Michael', 'Orlando'),
('Terry', 'Green'),
('Greg', 'Evans'),
('Sandy', 'Johnson'),
('Charlie', 'Jones'),
('Kevin', 'Grier'),
('Lani', 'Kulana'),
('Mary', 'Worley'),
('Tanya', 'Gleason'),
('Donna', 'Bradley'),
('Jimmy', 'Lawson'),
('Brenda', 'Fowler'),
('Karen', 'Mills'),
('Aretha', 'Gordon'),
('Carol', 'Brown'),
('Jerry', 'Freeman');